version: '3'
services:
  redis:
    image: bitnami/redis:latest
    env_file:
      - '.debug.env'
    ports:
      - '6379:6379'
    volumes:
      - ./.debug/redis/data:/bitnami/redis/data

  postgres:
    image: postgres:11-alpine
    env_file:
      - '.debug.env'
    ports:
      - 5432:5432
    volumes:
      - ./.debug/postgresql/data:/var/lib/postgresql/data

  # neutrino-open-api-starter:
  #   image: neutrino-open-api-starter
  #   build: .
  #   environment:
  #     NODE_ENV: development
  #   ports:
  #     - 3000:3000
  #     - 9229:9229
  #   ## set your startup file here
  #   command: npm run debug
