version: '2.1'

services:
  neutrino-open-api-starter:
    image: neutrino-open-api-starter
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    ## set your startup file here
    command: npm run debug
