@host=http://127.0.0.1:3000
###
{{host}}/api/v1/users

###
POST {{host}}/api/v1/users
Content-Type: application/json

{
  "userName": "AnsonT",
  "email": "test@ansont.me",
  "password": "password"
}

###
POST {{host}}/api/v1/login
Content-Type: application/json

{
  "userName": "AnsonT",
  "password": "passwoord"
}
