@host=http://example.localhost:3000
###
{{host}}/api/v1/users

###
POST {{host}}/api/v1/users
Content-Type: application/json

{
  "userName": "AnsonT",
  "email": "test@ansont.me",
  "password": "password"
}

###
POST {{host}}/api/v1/login
Content-Type: application/json

{
  "userName": "AnsonT",
  "password": "password"
}

###
PATCH {{host}}/api/v1/login
Content-Type: application/json

{
  "userName": "AnsonT",
  "oldPassword": "password2",
  "newPassword": "password"
}

###
{{host}}/api/v1/email/verify/ck4arlo9a000ik5sehc9y3xyc
