swagger: '2.0'
info:
  title: sample api doc
  version: '3'
basePath: '/v1'
paths:
  /foo:
    get:
      operationId: getFoo
      responses:
        default:
          description: return foo
          schema: {}
