logLevel:
  doc: 'The output log level'
  format: ['DEBUG', 'INFO', 'ERROR']
  default: 'INFO'
  env: 'LOG_LEVEL'
ip:
  doc: 'The IP address to bind'
  format: 'ipaddress'
  default: '127.0.0.1'
  env: 'IP_ADDRESS'

port:
  doc: 'The port to bind'
  format: 'port'
  default: 3000
  env: 'PORT'

db:
  password:
    doc: 'password'
    default: 'password'
    sensitive: true
