logLevel:
  doc: 'The output log level'
  format: ['DEBUG', 'INFO', 'ERROR']
  default: 'INFO'
  env: 'LOG_LEVEL'
ip:
  doc: 'The IP address to bind'
  format: 'ipaddress'
  default: '127.0.0.1'
  env: 'IP_ADDRESS'

port:
  doc: 'The port to bind'
  format: 'port'
  default: 3000
  env: 'PORT'

db:
  password:
    doc: 'password'
    default: 'password'
    sensitive: true

auth:
  defaultRole:
    doc: default role for new user
    default: user
    env: AUTH_DEFAULT_ROLE
  jwtIssuer:
    doc: issuer of jwt
    default: example.localhost
    env: AUTH_JWT_ISSUER
  jwtSecret:
    doc: jwt secret
    default: Don'tUseThis
    env: AUTH_JWT_SECRET
    sensitive: true
  jwtCookieDomain:
    doc: jwt cookie domain
    default: example.localhost
    env: AUTH_JWT_DOMAIN
  jwtCookie:
    doc: jwt cookie name
    default: auth_jwt
    env: AUTH_JWT_COOKIE
  jwtExpiresIn:
    doc: jwt expiration duration
    default: 1h
    env: AUTH_JWT_EXPIRES_IN

email:
  smtpHost:
    doc: email SMTP host
    default: smtp.gmail.com
    env: EMAIL_SMTP_HOST
  smtpPort:
    doc: email SMTP port
    default: 587
    env: EMAIL_SMTP_PORT
  smtpUser:
    doc: SMTP account user
    default: user
    env: EMAIL_SMTP_USER
  smtpPassword:
    doc: SMTP account password
    default: Don'tUseThis
    sensitive: true
    env: EMAIL_SMTP_PASSWORD
